apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-service-account
  namespace: fastapi-postgres
  labels:
    app: fastapi-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-service-account
  namespace: fastapi-postgres
  labels:
    app: postgres
automountServiceAccountToken: false